name: Security Monitor

on:
  schedule:
    # Her gün saat 09:00'da çalışır (UTC saat, Türkiye saati +3)
    - cron: '0 6 * * *'
  workflow_dispatch: # Manuel olarak da çalıştırabilirsiniz

jobs:
  check-security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run security monitor
      env:
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
      run: |
        python security_monitor.py
